/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidUdMTDZrQ1NlSlVqcTcrT2ZLb2lLNVpSS3cwcXIzUC8yQldLbnkrcWFHYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia2VZNURZTG1pNU53L1FYY29LMzJoWnZzR09DVm04MXRNQWJkcnp3ditEWT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJLSWtPTGNFaEtFLzNQRVA2a3hTR29yRG1tMXJROC8xMW43SG54VTJRbTI0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI3SDBtbU1tUTJNRG1QQ3ZjbFJJYUlOb2pKSWtCY1BOV05QYTBhcm9vckFBPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVDUjlJNEtuemhYdVFGak81UGJwNWt3djhQakhlUkpKRG9CVm9YK2tWV3M9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ilh5aXY0RnRpTHJINXp6ZnhXekg3bjQ2T1kwWmE2aVNFbzZxUEx4MGcram89In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY0FmeHI4eS9QVHBJMVRsK1gxS2hWT1czaUdHM1VESHZER0hjN3RzczZHND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYXV6R3QwL0VoOFp4Z1c4TDdKYmJ5VmRmK2JIWVdJUlAvS2UyK2pLUW9Haz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImJ6S3VmQ2ZPTTBFcGRacFJsQi8rU0tEQmN3U0ljeHd0bnNMbHpJL2k4OUorZThaem4zUEpwS2NsRWRQcytXNVRYYTJIUnlISU10VWxDUW1sTEk5RmhBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTQ3LCJhZHZTZWNyZXRLZXkiOiJFNkl1RTVxZWdSY0ZaaXVQaUp0alN1KzNUMWEwUTFKSjI2ckZLOTFscGdVPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjIzNzY5MTk2MzUxMEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBMzhFOUVDQ0ExRjQ3QzM3MkFDODlDQ0FGNDI1ODAwOSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzI5MTEwNjgzfSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyMzc2OTE5NjM1MTBAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiREFFMDNGRkRCNjExREJGOTIyNzc0MDdBRkU2N0JGQzAifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyOTExMDY4M31dLCJuZXh0UHJlS2V5SWQiOjMyLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzIsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiMEp5Q0Z1UHBTaE91WVVEc3drdE54dyIsInBob25lSWQiOiIyZDY1ZjNmNi1mOGFlLTRmOWYtOTM0ZC1jZDk0N2I2MjlkYzYiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT2J1MnZORTNLMVc0ZGliNEpsd3hUMUpuNlE4PSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlBhMEFFOWpXVTU4REhVU0thQ053NnBvZjk2Zz0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJYUlhQWkJHOCIsIm1lIjp7ImlkIjoiMjM3NjkxOTYzNTEwOjJAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiTeC+g+C/hmXgvoPgv4Zp4L6D4L+GIPCdkoDwnZKC8J2SjvCdkoLwnZKF8J2SgvCdkbXwnZKA8J2Rr/CdkajwnZGr8J2RrPCdkbrCssK5In0sImFjY291bnQiOnsiZGV0YWlscyI6IkNLenZ4a2NRODhUQXVBWVlBU0FBS0FBPSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJwQ2VYc0hVNGZ2bUZiOXJuS21YdGhDMFM0eFBLVEh5bE5CLzlWTFJtUjBRPSIsImFjY291bnRTaWduYXR1cmUiOiJZODRQNlp1bEYyN3BNWDNIcWM3TDFlSkJWNW42RTV4ZU5mT1VJOFZuckhGbDRaUExiR0ZzWDEyVUNMQmh2cjRqU3NYRlplaVpaMktNeUYyWW1XTUFBUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoieTMzenJHRHlBUEVwMGVGZ3BROVl3Szgzc1c2T2VWZ3hkbi9rdFlscEtnek5IdEI0cmJ0bm9QR1lQMEhza2xmSHFKY09EcEQ4YUswNStKbEZJUjZ4aVE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzc2OTE5NjM1MTA6MkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJhUW5sN0IxT0g3NWhXL2E1eXBsN1lRdEV1TVR5a3g4cFRRZi9WUzBaa2RFIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzI5MTEwNjU3LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUp5QiJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'fortunatus';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '254114018035';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DREADED';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
